//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginEx.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_4
    {
        public int ID { get; set; }
        public string Role { get; set; }
    
        public virtual Table_1 Table_1 { get; set; }
    }
}
